# Generated by Django 3.2.25 on 2024-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='allergy',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrient',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
